application:
  environment: develop
  name: octolytics-core
  partOf: octolytics

replicaCount: 1

autoscaling:
  enabled: true
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 25
  targetMemoryUtilizationPercentage: 80

extraLabels:
  admission.datadoghq.com/enabled: "true"
  tags.datadoghq.com/env: develop
  tags.datadoghq.com/service: octolytics-octolytics-core

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: octolytics-us-central1-sa@octolytics-core.iam.gserviceaccount.com
  create: true
  name: octolytics-core

externalSecrets:
  enabled: true
  refreshInterval: 15s
  secretStoreRef:
    name: gcp-backend
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: api.octolytics.develop.octolytics-core.com
      paths:
        - path: /
          pathType: Prefix
          container: api
          port: http
  tls: []

envs: []

imagePullSecrets: []
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
affinity: {}
tolerations: []

containers: []
