apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "octolytics-core.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gcp-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "octolytics-core.fullname" . }}
  data:
  {{- range $k, $v := .Values.secrets }}
    - secretKey: {{ $v.env }}
      remoteRef:
        key: {{ $.Values.application.name }}-{{ $.Values.application.environment }}-{{ $v.key }}
  {{- end }}