apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "octolytics-core.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gcp-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "octolytics-core.fullname" . }}
  data:
  {{- range .Values.secrets }}
  {{- if not .mountPath }}
    - secretKey: {{ .env }}
      remoteRef:
        key: {{ .key }}
  {{- end }}
  {{- end }}
---
{{- $secretsWithMountPath := list -}}
{{- range .Values.secrets -}}
{{- if .mountPath -}}
{{- $secretsWithMountPath = append $secretsWithMountPath . -}}
{{- end -}}
{{- end -}}

{{- if gt (len $secretsWithMountPath) 0 -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "octolytics-core.fullname" . }}-mount
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gcp-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "octolytics-core.fullname" . }}-mount
  data:
  {{- range $secretsWithMountPath }}
    - secretKey: {{ .env }}
      remoteRef:
        key: {{ .key }}
  {{- end }}
{{- end }}